# Generated by Django 3.1 on 2020-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_tag_slug'),
        ('project', '0002_auto_20200914_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='post.Tag'),
        ),
    ]
